language: python

python:
  - "2.7"

before_install:

- pip install coverage

install: python setup.py install

script: coverage run -m unittest discover pyArango/tests/

after_success: bash <(curl -s https://codecov.io/bash)
