language: python

python:
  - "2.7"

addons:
    apt:
        packages:
            - liblapack-dev
            - gfortran

install:
  - pip install coverage
  - python setup.py install

script: coverage run -m unittest discover pyArango/tests/

after_success: bash <(curl -s https://codecov.io/bash)
